import { readFileSync, writeFileSync } from 'fs';

const existing = readFileSync('src/app/lib/cms-store.ts', 'utf8');
const L = existing.split('\n');

const a = (...args) => args.forEach(l => L.push(l));

a(
"",
"// ── Initial Data ─────────────────────────────────────────────────",
"",
"export const useCMSStore = create<CMSStore>((set) => ({",
"  // Company",
"  companyInfo: {",
"    name: 'BASE SECURITY, CLEANING & TRADING PLC',",
"    taglineAmharic: '\u1260\u12d8 \u1208\u120b\u1240 \u12e8\u12f0\u1205\u1295\u1290\u1275 \u12a0\u1308\u120d\u130d\u120e\u1275',",
"    taglineEnglish: 'Base Excellence Security Service',",
"    whatsappNumber: '251911234038',",
"  },",
"  updateCompanyInfo: (info) => set((state) => ({ companyInfo: { ...state.companyInfo, ...info } })),",
"",
"  // Hero",
"  heroContent: {",
"    badge: '\u1260\u12d8 \u1208\u120b\u1240 \u12e8\u12f0\u1205\u1295\u1290\u1275 \u12a0\u1308\u120d\u130d\u120e\u1275',",
"    title: 'BASE SECURITY,',",
"    highlightWord: 'CLEANING',",
"    subtitle: 'Your trusted partner for professional security services and cleaning solutions in Addis Abeba. On-demand, reliable, and certified.',",
"    primaryButtonText: 'Request a Service',",
"    secondaryButtonText: 'Contact Us',",
"    backgroundImage: 'https://images.unsplash.com/photo-1761064392859-2bfa734e9f3f?w=1080&q=80',",
"  },",
"  updateHeroContent: (content) => set((state) => ({ heroContent: { ...state.heroContent, ...content } })),",
"",
"  // Stats",
"  stats: [",
"    { id: 's1', value: 500, suffix: '+', label: 'Trained Professionals' },",
"    { id: 's2', value: 200, suffix: '+', label: 'Satisfied Clients' },",
"    { id: 's3', value: 10, suffix: '+', label: 'Years Experience' },",
"    { id: 's4', value: 24, suffix: '/7', label: 'Service Availability' },",
"  ],",
"  addStat: (stat) => set((state) => ({ stats: [...state.stats, { ...stat, id: `stat-${Date.now()}` }] })),",
"  updateStat: (id, updates) => set((state) => ({ stats: state.stats.map((s) => s.id === id ? { ...s, ...updates } : s) })),",
"  deleteStat: (id) => set((state) => ({ stats: state.stats.filter((s) => s.id !== id) })),",
"",
"  // Testimonials",
"  testimonials: [",
"    { id: 't1', name: 'Ato Dawit Bekele', company: 'Ethio Telecom', role: 'Security Manager', content: 'BASE SECURITY has been protecting our headquarters for over a year. Their professionalism and reliability are unmatched in Addis Abeba.', rating: 5 },",
"    { id: 't2', name: 'W/ro Meron Tadesse', company: 'Hilton Addis Abeba', role: 'Operations Director', content: 'Their housekeeping and cleaning team keeps our hotel spotless. Punctual, thorough, and always professional.', rating: 5 },",
"    { id: 't3', name: 'Ato Abebe Girma', company: 'Commercial Bank of Ethiopia', role: 'Facilities Director', content: 'Both the cleaning and security services transformed our workplace. We rely on BASE for everything facility-related.', rating: 5 },",
"  ],",
"  addTestimonial: (t) => set((state) => ({ testimonials: [...state.testimonials, { ...t, id: `test-${Date.now()}` }] })),",
"  updateTestimonial: (id, updates) => set((state) => ({ testimonials: state.testimonials.map((t) => t.id === id ? { ...t, ...updates } : t) })),",
"  deleteTestimonial: (id) => set((state) => ({ testimonials: state.testimonials.filter((t) => t.id !== id) })),",
"",
"  // Client Logos",
"  clientLogos: [",
"    { id: 'cl1', name: 'Ethio Telecom', initials: 'ET', color: '#0066cc' },",
"    { id: 'cl2', name: 'Hilton Addis Abeba', initials: 'HA', color: '#003087' },",
"    { id: 'cl3', name: 'Commercial Bank of Ethiopia', initials: 'CB', color: '#006633' },",
"    { id: 'cl4', name: 'Ethiopian Airlines', initials: 'EA', color: '#009900' },",
"    { id: 'cl5', name: 'Sheraton Addis', initials: 'SA', color: '#8B0000' },",
"    { id: 'cl6', name: 'Awash Bank', initials: 'AB', color: '#FF6600' },",
"    { id: 'cl7', name: 'Dashen Bank', initials: 'DB', color: '#003366' },",
"    { id: 'cl8', name: 'Bole International Hotel', initials: 'BI', color: '#6B3A2A' },",
"    { id: 'cl9', name: 'Addis Abeba University', initials: 'AU', color: '#4B0082' },",
"    { id: 'cl10', name: 'Safaricom Ethiopia', initials: 'SE', color: '#4CAF50' },",
"  ],",
"  addClientLogo: (c) => set((state) => ({ clientLogos: [...state.clientLogos, { ...c, id: `logo-${Date.now()}` }] })),",
"  updateClientLogo: (id, updates) => set((state) => ({ clientLogos: state.clientLogos.map((c) => c.id === id ? { ...c, ...updates } : c) })),",
"  deleteClientLogo: (id) => set((state) => ({ clientLogos: state.clientLogos.filter((c) => c.id !== id) })),"
);

writeFileSync('src/app/lib/cms-store.ts', L.join('\n'), 'utf8');
console.log('Part 2 written: ' + L.length + ' lines');
